# Generated by Django 3.2.9 on 2021-11-30 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribuicoesporparticipante',
            options={'verbose_name': 'ContribuicaoPorParticipante', 'verbose_name_plural': '>>Comece preenchendo por aqui!<<'},
        ),
        migrations.AlterUniqueTogether(
            name='mecanismodeparticipacao',
            unique_together={('agencia', 'dataInicialContribuicoes', 'nomenclaturaDadaPelaAgencia')},
        ),
    ]
