# Generated by Django 3.2.9 on 2022-01-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211130_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriasparticipante',
            name='categoria',
            field=models.CharField(max_length=120, unique=True, verbose_name='Categoria participante'),
        ),
        migrations.AlterField(
            model_name='indexacaotema',
            name='indexacaoTema',
            field=models.CharField(max_length=10, unique=True, verbose_name='Indexacao tema'),
        ),
        migrations.AlterField(
            model_name='instrumentodeparticipacao',
            name='instrumentoDeParticipacao',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='monitoracao',
            name='monitorar',
            field=models.CharField(default='#', max_length=10, unique=True, verbose_name='Monitorar'),
        ),
        migrations.AlterField(
            model_name='objetivoparticipacao',
            name='objetivo',
            field=models.TextField(unique=True, verbose_name='Objetivo'),
        ),
        migrations.AlterField(
            model_name='subcategoriasparticipante',
            name='subCategoria',
            field=models.CharField(max_length=120, unique=True, verbose_name='Sub categoria participante'),
        ),
        migrations.AlterField(
            model_name='subsubcategoriasparticipante',
            name='subSubCategoria',
            field=models.CharField(max_length=120, unique=True, verbose_name='Sub sub categoria participante'),
        ),
        migrations.AlterField(
            model_name='subsubsubcategoriasparticipante',
            name='subSubSubCategoria',
            field=models.CharField(max_length=120, unique=True, verbose_name='Sub sub sub categoria participante'),
        ),
        migrations.AlterField(
            model_name='tipodadopelaagencia',
            name='tipo',
            field=models.CharField(max_length=200, unique=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='tipoDocumento',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tipo do documento'),
        ),
        migrations.AlterUniqueTogether(
            name='agencia',
            unique_together={('nome', 'sigla')},
        ),
        migrations.AlterUniqueTogether(
            name='documento',
            unique_together={('mecanismo', 'tipoDocumento', 'dataDocumento')},
        ),
        migrations.AlterUniqueTogether(
            name='intermediariotemamecanismo',
            unique_together={('mecanismo', 'indexacaoTema')},
        ),
    ]
