# Generated by Django 3.2.9 on 2022-01-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220104_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='sigla',
            field=models.CharField(max_length=20, unique=True, verbose_name='Sigla'),
        ),
        migrations.AlterUniqueTogether(
            name='agencia',
            unique_together=set(),
        ),
    ]
