# Generated by Django 3.2.9 on 2022-04-13 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_monitoracao_monitorar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mecanismodeparticipacao',
            unique_together={('agencia', 'dataInicialContribuicoes', 'nomenclaturaDadaPelaAgencia', 'ementa')},
        ),
    ]
