# Generated by Django 3.2.9 on 2022-04-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220412_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanismodeparticipacao',
            name='indexacaoSubtema',
            field=models.CharField(max_length=2001, verbose_name='Indexação subtema'),
        ),
    ]
