# Generated by Django 3.2.9 on 2022-04-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_mecanismodeparticipacao_indexacaosubtema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoriasparticipante',
            name='subCategoria',
            field=models.CharField(max_length=121, unique=True, verbose_name='Sub categoria participante'),
        ),
        migrations.AlterField(
            model_name='subsubcategoriasparticipante',
            name='subSubCategoria',
            field=models.CharField(max_length=122, unique=True, verbose_name='Sub sub categoria participante'),
        ),
        migrations.AlterField(
            model_name='subsubsubcategoriasparticipante',
            name='subSubSubCategoria',
            field=models.CharField(max_length=123, unique=True, verbose_name='Sub sub sub categoria participante'),
        ),
    ]
