# Generated by Django 3.2.9 on 2022-04-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220424_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoriasparticipante',
            name='subCategoria',
            field=models.CharField(max_length=1210, unique=True, verbose_name='Sub categoria participante'),
        ),
    ]
