# Generated by Django 3.2.9 on 2022-04-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_contribuinte_personalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuinte',
            name='antigoIdInterno',
            field=models.TextField(default=None, null=True, verbose_name='ID Interno gerado no antigo sistemas de dados armazenados em CSV (OPCIONAL)'),
        ),
        migrations.AddField(
            model_name='mecanismodeparticipacao',
            name='antigoIdInterno',
            field=models.TextField(default=None, null=True, verbose_name='ID Interno gerado no antigo sistemas de dados armazenados em CSV (OPCIONAL)'),
        ),
    ]
