# Generated by Django 3.2.9 on 2022-04-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220425_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuinte',
            name='nome',
            field=models.CharField(max_length=204, unique=True, verbose_name='Nome do contribuinte'),
        ),
        migrations.AlterUniqueTogether(
            name='contribuinte',
            unique_together={('categoria', 'subCategoria', 'subSubCategoria', 'subSubSubCategoria', 'agencia', 'nome')},
        ),
    ]
