# Generated by Django 3.2.9 on 2022-04-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220425_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuinte',
            name='nome',
            field=models.CharField(max_length=204, verbose_name='Nome do contribuinte'),
        ),
    ]
