# Generated by Django 3.2.9 on 2022-04-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_contribuinte_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuinte',
            name='nomeUpper',
            field=models.CharField(default='', max_length=204, verbose_name='Nome do contribuinte em caixa alta (capslocks)'),
            preserve_default=False,
        ),
    ]
