# Generated by Django 3.2.9 on 2022-04-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_contribuinte_nomeupper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribuinte',
            name='antigoIdInterno',
        ),
        migrations.AlterField(
            model_name='mecanismodeparticipacao',
            name='antigoIdInterno',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='ID Interno gerado no antigo sistemas de dados armazenados em CSV (OPCIONAL)'),
        ),
    ]
